sudo: false
language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
        - libevent-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-$TRAVIS_PYTHON_VERSION.txt
# command to run tests
script: nosetests tests/unit tests/integration
